### ISSUE TITLE
Add a page to the web UI to show song list

### ISSUE THREAD

**Issue by louis6321** [udoprog/setmod#3]
Given the character limit per message in chat, it would be good if I could see the full song list via the web UI.
It would also be easier to read given everything is basically one big paragraph in Twitch chat.

**Comment by udoprog** [comment]
You can now add the following to the configuration (assuming you've built the latest player):

```toml
api_url = "https://setbac.tv"
```

And your playlist will show up on a page like https://setbac.tv/player/setbac with your twitch username.

Note: This feature uses your Twitch token to authenticate with `setbac.tv`. Request sizes are limited and playlist are not stored forever. Only the current session.
